import  "bootstrap/dist/css/bootstrap.min.css"
import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import '@/app/globals.css';
import AddBootstrap from "@/utils/bootstrap/AddBootstrap";

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={poppins.className}>
        <AddBootstrap/>
        {children}
      </body>
    </html>
  );
}
